### ISSUE TITLE
AssertionError: Range subprocess failed (exit code: 1)

### ISSUE THREAD

**Issue by MenGuangwen-CN-0411** [yihui-he/KL-Loss#17]
### System information
* Operating system: ubuntu16.04 
* CUDA version: 9.0
  pytorch 1.0
 1080ti x 1
when I run:  python2 tools/test_net.py -c configs/e2e_faster_rcnn_R-50-FPN_2x.yaml
I just get :
```
Traceback (most recent call last):
  File "/home/user/softer_nms/tools/test_net.py", line 113, in <module>
    check_expected_results=True,
  File "/home/user/softer_nms/detectron/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/home/user/softer_nms/detectron/core/test_engine.py", line 125, in result_getter
    gpu_id=gpu_id
  File "/home/user/softer_nms/detectron/core/test_engine.py", line 235, in test_net
    model = initialize_model_from_cfg(weights_file, gpu_id=gpu_id)
  File "/home/user/softer_nms/detectron/core/test_engine.py", line 330, in initialize_model_from_cfg
    model, weights_file, gpu_id=gpu_id,
  File "/home/user/softer_nms/detectron/utils/net.py", line 62, in initialize_gpu_from_weights_file
    src_blobs = load_object(weights_file)
  File "/home/user/softer_nms/detectron/utils/io.py", line 60, in load_object
    return pickle.load(f)
EOFError
Traceback (most recent call last):
  File "tools/test_net.py", line 113, in <module>
    check_expected_results=True,
  File "/home/user/softer_nms/detectron/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/home/user/softer_nms/detectron/core/test_engine.py", line 108, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/user/softer_nms/detectron/core/test_engine.py", line 155, in test_net_on_dataset
    weights_file, dataset_name, proposal_file, num_images, output_dir
  File "/home/user/softer_nms/detectron/core/test_engine.py", line 188, in multi_gpu_test_net_on_dataset
    'detection', num_images, binary, output_dir, opts
  File "/home/user/softer_nms/detectron/utils/subprocess.py", line 95, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home/user/softer_nms/detectron/utils/subprocess.py", line 133, in log_subprocess_output
     assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 1)
```
How to modify this bug

**Comment by ethanhe42** [comment]
there's problem loading the pickle `pickle.load(f) EOFError`. this is a problem with the machine
